// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../../APP/Effect/Inc/effect.h"
lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Arc2 = NULL;
lv_obj_t * ui_Arc3 = NULL;
lv_obj_t * ui_Arc4 = NULL;
lv_obj_t * ui_Button11 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Button12 = NULL;
// event funtions
lv_obj_t * Arc[3];
void ui_event_Arc(lv_event_t * e)
{
    lv_obj_t * target = lv_event_get_target(e);
    lv_event_code_t event_code = lv_event_get_code(e);
    effect_all_t* effect_buffer = effect_buffer_get();
    for (uint8_t i = 0; i < 3; i++)
    {
        if (target == Arc[i])
        {
            if(event_code == LV_EVENT_VALUE_CHANGED)
            {
                uint8_t Value = (uint8_t)lv_arc_get_value(Arc[i]);
                effect_buffer[ui_get_Button_Num()].Effect->param[i] = Value;
            }
        }
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc2 = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_Arc2, 150);
    lv_obj_set_height(ui_Arc2, 150);
    lv_obj_set_x(ui_Arc2, -260);
    lv_obj_set_y(ui_Arc2, -40);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc2, 50);

    ui_Arc3 = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_Arc3, 150);
    lv_obj_set_height(ui_Arc3, 150);
    lv_obj_set_x(ui_Arc3, 0);
    lv_obj_set_y(ui_Arc3, -40);
    lv_obj_set_align(ui_Arc3, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc3, 50);

    ui_Arc4 = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_Arc4, 150);
    lv_obj_set_height(ui_Arc4, 150);
    lv_obj_set_x(ui_Arc4, 260);
    lv_obj_set_y(ui_Arc4, -40);
    lv_obj_set_align(ui_Arc4, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc4, 50);

    ui_Button11 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button11, 100);
    lv_obj_set_height(ui_Button11, 94);
    lv_obj_set_x(ui_Button11, 0);
    lv_obj_set_y(ui_Button11, 170);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label1, 90);
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -262);
    lv_obj_set_y(ui_Label1, -153);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label2, 90);
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -3);
    lv_obj_set_y(ui_Label2, -151);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label3, 90);
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 257);
    lv_obj_set_y(ui_Label3, -147);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button12 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button12, 100);
    lv_obj_set_height(ui_Button12, 50);
    lv_obj_set_x(ui_Button12, -332);
    lv_obj_set_y(ui_Button12, -208);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_Arc2, ui_event_Arc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Arc2, ui_event_Arc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Arc2, ui_event_Arc, LV_EVENT_ALL, NULL);
    Arc[0] = ui_Arc2;
    Arc[1] = ui_Arc3;
    Arc[2] = ui_Arc4;
}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Arc2 = NULL;
    ui_Arc3 = NULL;
    ui_Arc4 = NULL;
    ui_Button11 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_Button12 = NULL;

}
