// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project
#include <stdio.h>

#include "stdint.h"
#include "../ui.h"
#include "../../Effect/Inc/effect.h"
lv_obj_t* ui_Screen2 = NULL;
lv_obj_t* ui_Roller1 = NULL;
lv_obj_t* ui_Button9 = NULL;
lv_obj_t* ui_Button10 = NULL;
// event funtions
void ui_event_Button9(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {

        uint8_t Button_Num = ui_get_Button_Num();
        effect_process_t* effect_buffer = effect_buffer_get();
        uint8_t roller_num= lv_roller_get_selected(ui_Roller1);
        effect_t** effect_all_buffer = effect_get();

        if (Button_Num >= 8 ||roller_num >= 32 ||effect_all_buffer[roller_num] == NULL)
        {
            return;
        }

        effect_buffer->Effect[Button_Num] = *effect_all_buffer[roller_num];
        effect_buffer->Effect[Button_Num].enable = 1;   /* 选中即开启 */
        effect_buffer->Effect[Button_Num].Init(&effect_buffer->Effect[Button_Num]);

        lv_label_set_text(Label[Button_Num], effect_buffer->Effect[Button_Num].name);
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button10(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);

    ui_Roller1 = lv_roller_create(ui_Screen2);

    effect_init();
    effect_t** effect_buffer = effect_get();
    static char roller_string[256];
    size_t offset = 0;

    roller_string[0] = '\0';

    for (uint8_t i = 0; i < 32; i++)
    {
        if (effect_buffer[i] == NULL)
        {
            continue;
        }

        int written = snprintf(roller_string + offset,256 - offset,"%s%s",offset == 0 ? "" : "\n",effect_buffer[i]->name);
        if (written < 0)
        {
            break;
        }
        if ((size_t)written >= 256 - offset)
        {
            offset = 256 - 1;
            break;
        }
        offset += (size_t)written;
    }
    roller_string[offset] = '\0';
    lv_roller_set_options(ui_Roller1,roller_string,LV_ROLLER_MODE_NORMAL);


    //lv_roller_set_options(ui_Roller1, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller1, 397);
    lv_obj_set_height(ui_Roller1, 476);
    lv_obj_set_x(ui_Roller1, -17);
    lv_obj_set_y(ui_Roller1, -3);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);

    ui_Button9 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button9, 100);
    lv_obj_set_height(ui_Button9, 50);
    lv_obj_set_x(ui_Button9, 334);
    lv_obj_set_y(ui_Button9, 198);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Button10 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button10, 100);
    lv_obj_set_height(ui_Button10, 50);
    lv_obj_set_x(ui_Button10, -339);
    lv_obj_set_y(ui_Button10, -204);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
}

void ui_Screen2_screen_destroy(void)
{
    if (ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Roller1 = NULL;
    ui_Button9 = NULL;
    ui_Button10 = NULL;
}
